-- CREATE TABLE DEMO_STATES(
-- 	ST VARCHAR PRIMARY KEY,
-- 	STATE_NAME VARCHAR
-- );
--
-- INSERT INTO DEMO_STATES VALUES (	'AK','ALASKA'	);
-- INSERT INTO DEMO_STATES VALUES (	'AL','ALABAMA'	);
-- INSERT INTO DEMO_STATES VALUES (	'AR','ARKANSAS'	);
-- INSERT INTO DEMO_STATES VALUES (	'AZ','ARIZONA'	);
-- INSERT INTO DEMO_STATES VALUES (	'CA','CALIFORNIA'	);
-- INSERT INTO DEMO_STATES VALUES (	'CO','COLORADO'	);
-- INSERT INTO DEMO_STATES VALUES (	'CT','CONNECTICUT'	);
-- INSERT INTO DEMO_STATES VALUES (	'DC','DISTRICT OF COLUMBIA'	);
-- INSERT INTO DEMO_STATES VALUES (	'DE','DELAWARE'	);
-- INSERT INTO DEMO_STATES VALUES (	'FL','FLORIDA'	);
-- INSERT INTO DEMO_STATES VALUES (	'GA','GEORGIA'	);
-- INSERT INTO DEMO_STATES VALUES (	'HI','HAWAII'	);
-- INSERT INTO DEMO_STATES VALUES (	'IA','IOWA'	);
-- INSERT INTO DEMO_STATES VALUES (	'ID','IDAHO'	);
-- INSERT INTO DEMO_STATES VALUES (	'IL','ILLINOIS'	);
-- INSERT INTO DEMO_STATES VALUES (	'IN','INDIANA'	);
-- INSERT INTO DEMO_STATES VALUES (	'KS','KANSAS'	);
-- INSERT INTO DEMO_STATES VALUES (	'KY','KENTUCKY'	);
-- INSERT INTO DEMO_STATES VALUES (	'LA','LOUISIANA'	);
-- INSERT INTO DEMO_STATES VALUES (	'MA','MASSACHUSETTS'	);
-- INSERT INTO DEMO_STATES VALUES (	'MD','MARYLAND'	);
-- INSERT INTO DEMO_STATES VALUES (	'ME','MAINE'	);
-- INSERT INTO DEMO_STATES VALUES (	'MI','MICHIGAN'	);
-- INSERT INTO DEMO_STATES VALUES (	'MN','MINNESOTA'	);
-- INSERT INTO DEMO_STATES VALUES (	'MO','MISSOURI'	);
-- INSERT INTO DEMO_STATES VALUES (	'MS','MISSISSIPPI'	);
-- INSERT INTO DEMO_STATES VALUES (	'MT','MONTANA'	);
-- INSERT INTO DEMO_STATES VALUES (	'NC','NORTH CAROLINA'	);
-- INSERT INTO DEMO_STATES VALUES (	'ND','NORTH DAKOTA'	);
-- INSERT INTO DEMO_STATES VALUES (	'NE','NEBRASKA'	);
-- INSERT INTO DEMO_STATES VALUES (	'NH','NEW HAMPSHIRE'	);
-- INSERT INTO DEMO_STATES VALUES (	'NJ','NEW JERSEY'	);
-- INSERT INTO DEMO_STATES VALUES (	'NM','NEW MEXICO'	);
-- INSERT INTO DEMO_STATES VALUES (	'NV','NEVADA'	);
-- INSERT INTO DEMO_STATES VALUES (	'NY','NEW YORK'	);
-- INSERT INTO DEMO_STATES VALUES (	'OH','OHIO'	);
-- INSERT INTO DEMO_STATES VALUES (	'OK','OKLAHOMA'	);
-- INSERT INTO DEMO_STATES VALUES (	'OR','OREGON'	);
-- INSERT INTO DEMO_STATES VALUES (	'PA','PENNSYLVANIA'	);
-- INSERT INTO DEMO_STATES VALUES (	'RI','RHODE ISLAND'	);
-- INSERT INTO DEMO_STATES VALUES (	'SC','SOUTH CAROLINA'	);
-- INSERT INTO DEMO_STATES VALUES (	'SD','SOUTH DAKOTA'	);
-- INSERT INTO DEMO_STATES VALUES (	'TN','TENNESSEE'	);
-- INSERT INTO DEMO_STATES VALUES (	'TX','TEXAS'	);
-- INSERT INTO DEMO_STATES VALUES (	'UT','UTAH'	);
-- INSERT INTO DEMO_STATES VALUES (	'VA','VIRGINIA'	);
-- INSERT INTO DEMO_STATES VALUES (	'VT','VERMONT'	);
-- INSERT INTO DEMO_STATES VALUES (	'WA','WASHINGTON'	);
-- INSERT INTO DEMO_STATES VALUES (	'WI','WISCONSIN'	);
-- INSERT INTO DEMO_STATES VALUES (	'WV','WEST VIRGINIA'	);
-- INSERT INTO DEMO_STATES VALUES (	'WY','WYOMING'	);
--
-- COMMIT;

CREATE or replace FUNCTION upperDemoStates() RETURNS TRIGGER AS $$
BEGIN
    NEW.st = UPPER(NEW.st);
    NEW.state_name = UPPER(NEW.state_name);
    return NEW;
END
$$ LANGUAGE plpgsql;


CREATE Trigger demoStatesToUpper
Before INSERT Or UPDATE on demo_states for each row
execute procedure upperDemoStates();

insert into demo_states values ('aa','ffde');
update demo_states set state_name='tunis' where demo_states.st='AA';
select * from demo_states where st LIKE 'AA';

